version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"                # Location of package.json / yarn.lock
    schedule:
      interval: "weekly"          # Can be "daily", "weekly", or "monthly"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "react"
        versions: ["17.x"]

  # Optional: For GitHub Actions (if you're using them)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
