apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: sysco
    description: Sysco Corporation (SYY) is the world's largest broadline food distributor
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: kezri29/Java-Practice
    tags:
        - javascript
    links:
        - url: https://admin.example-org.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: service
    lifecycle: development
    owner: prodapt
    system: project-x
