apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: GEN-AI
    description: GEN-AI
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: pep8speaks-org/pep8speaks
    tags:
        - javascript
    links:
        - url: https://admin.example-org.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: service
    lifecycle: development
    owner: meeran
    system: project-x
