apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sysco
  description: Sysco Corporation (SYY) is the world's largest broadline food distributor
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: pep8speaks-org/pep8speaks
    snyk.io/org-id: a1d16401-496b-4613-acc4-6fbe0e76ed8c
  tags:
    - javascript
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: development
  owner: prodapt
  system: project-x
