apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: API for my-service with real-time Swagger documentation
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
  definition:
    $text: https://my.service.com/docs/docs.yaml
